services:
  # PostgreSQL Database Service
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]  # Healthcheck for PostgreSQL
        interval: 60s
        timeout: 10s
        retries: 5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data #persisting data 
            
  # pgAdmin Service
  pgadmin:  
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80 # for local browser (80 is the default port of the browsed)
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin  # Persisting pgAdmin configuration and sessions
    depends_on: 
      - db

  # ETL Service
  etl:
    container_name: etl
    build:
      context: ./project/etl
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
        - ./project/etl:/etl
    depends_on: 
      db:
        condition: service_healthy
    healthcheck:
      test: "exit 0"

  # FastAPI Backend Service
  api:
    build:
      context: ./project/api
      dockerfile: Dockerfile
    volumes:
      - ./project/api:/api
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    
  app:
    container_name: streamlit_app
    build:
      context: ./project/app
      dockerfile: Dockerfile
    volumes:
      - ./project/app:/app
    ports:
      - 8501:8501
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api

networks:
  default:
    driver: bridge


